### ISSUE TITLE
USER STORY (#2) : Initial Django project setup

### ISSUE THREAD

**Issue by yamesjamess** [yamesjamess/p4-roller-criu#14]
As a **developer** I can **set up the developing environment and deploy to Heroku** so that **I can solve any deployment issue that arises early on**

Epic #2 

Acceptance criteria

1. Given that I am the developer. I want to create a repository on my GitHub using the Code Institute's template.
2. Given that I am the developer. I want to utilise GitHub's Project and Issues functions so that I can develop the project with the agile development methodology.
3. Given that I am the developer. I want to be able to label each user's stories, tasks, and issues to prioritise them so that I can progress with the development incrementally.
4. Given that I am the developer. I want to deploy the project from the beginning to Heruko so that I can identify any issues with the deployment.

Tasks

- [x] Create GitHub Repository
- [x] Create Project Board and User Story templates
- [x] Create EPICs and User Stroy and add them to the board
- [x] Create an empty Readme template
- [x] Setup the project with all the requirement libraries (Django, PostgreSQL, Cloudinary, Gunicorn,)
- [x] Create Static files
- [x] Create SQL Database
- [x] Create Secret Key
- [x] Create env.py and add it to git.ignore
- [x] Create Heruku Project
- [x] Early Deployment

**Comment by yamesjamess** [comment]
The app was successfully deployed to Heroku.

**Comment by yamesjamess** [comment]
media, static, and templates folder created
