### ISSUE TITLE
USER STORY (#3) : Create bootstrap template

### ISSUE THREAD

**Issue by yamesjamess** [yamesjamess/p4-roller-criu#15]
As a **developer** I can **create an essential website using Bootstrap** so that **it meets my site's requirements**

Acceptance Criteria
1. Given that I am the developer, I want to create a template using bootstrap based on the wireframe prototype, so that I can structure the website accordingly.
2. Given that I am the user, I want to be able to navigate the site easily, with all the functions of the website functioning correctly, so that I can go where I want to on the website.

Task
- [x] Create base.html
- [x] Create header
- [x] Create footer
- [x] Create navbar
- [x] Create home page
- [x] Create about page
- [x] Create detail lesson page
- [x] Create contact page
- [x] Create account login page
- [x] Create account register page
- [ ] Create forgot password page (optional)
- [x] Create create booking form

**Comment by yamesjamess** [comment]
All Lesson page removed from project
