### ISSUE TITLE
USER STORY (#4) : Create Class Model

### ISSUE THREAD

**Issue by yamesjamess** [yamesjamess/p4-roller-criu#16]
As a **admin user** I can **create class details** so that **they can be published on to the front end of the website**

EPIC #4 

Acceptance Criteria

1. Given that I am the admin, I can log in via the Django admin area and create a new class.
2. Given that I am the admin, I can publish or unpublish classes.
3. Given that I am the admin, I can edit or delete the classes.
4. Given that I am the front-end user, I can see all the classes that have been published.

Task

- [ ] Create roller criu app
- [ ] Create the class model and database fields.
- [ ] Create template for class and all_classes page.
- [ ] Host pictures on cloudinary
- [ ] Migrate database
- [ ] Create URLs
- [ ] Add URL paths to the project URL file.
- [ ] Create views
- [ ] Add pagination for more than 6 classes
