### ISSUE TITLE
USER STORY (#7) : View class information

### ISSUE THREAD

**Issue by yamesjamess** [yamesjamess/p4-roller-criu#25]
As a **Site User** I can **c;ick on a Class** so that **view the full details of the class**

Acceptance Criteria

1. Image, title, location, date/time, and detailed description are displayed on the screen.
2. Coach image, name, and brief information are displayed on the screen.
3. The function to book the class is available

**Comment by yamesjamess** [comment]
- [ ] Image, title, location, date/time, and detailed description are displayed on the screen.
- [ ] Coach image, name, and brief information are displayed on the screen.
- [ ] The function to book the class is available
