### ISSUE TITLE
USER STORY (#23) : Create Automatic Testing

### ISSUE THREAD

**Issue by yamesjamess** [yamesjamess/p4-roller-criu#49]
As a **developer** I can **creat automatic testing** so that **verify that my code is running correctly**

Acceptance Criteria

- [x] Passing test on admin.py
- [x] Passing test on forms.py
- [x] Passing test on models.py
- [x] Passing test on views.py

**Comment by yamesjamess** [comment]
test form is completed

**Comment by yamesjamess** [comment]
test view is partially complete. Getting error 404 when trying to get lesson_detail page. Trying to resolve it with tutors

**Comment by yamesjamess** [comment]
test model is partially complete, need to reset database and emigrate model changes

**Comment by yamesjamess** [comment]
test admin partially complete. Bug on unapproveing Booking and Feedback

**Comment by yamesjamess** [comment]
test view completed

**Comment by yamesjamess** [comment]
completed and verified
