### ISSUE TITLE
USER STORY (#1) : Gather ideas and general requirements for the project

### ISSUE THREAD

**Issue by yamesjamess** [yamesjamess/p4-roller-criu#5]
As a **developer** I can **visualise how the website should be** so that **develop the website methodically**

EPIC #1 

Acceptance criteria

1.  Given that I am the developer, I want to be able to understand what the goals of the site are.
2.  Given that I am the developer, I want to have a clear visual plan of how the site should look on the front end and their journey
3.  Given that I am the developer, I want to understand the relationship between each database models

Task

- [x] Create wireframe
- [x] Create database entity relationship chart and schematics
- [x] Research bootstrap templates
- [x] Choose font family(s)
- [x] Create Logo
- [x] Decide on colour scheme
- [x] Gather graphic assets (images, icons, favicons, etc.)
- [x] Write content for the page

**Comment by yamesjamess** [comment]
About Us
Roller Criú, a pioneering roller skating initiative, was born out of Roisin Smith's passion and determination in the year 2020. Faced with the frustrating realization that there was no formal establishment dedicated to teaching the art of roller skating, Roisin decided to take matters into her own hands. Fuelled by her love for roller skating and a desire to share it with others, she founded Roller Criú. This unique venture was designed to cater to everyone, from those taking their first tentative steps on wheels to those aiming for competition-level skills. Through a combination of dedication, innovative teaching methods, and a welcoming atmosphere, Roller Criú has since become a thriving community and a go-to destination for roller skaters of all levels, ensuring that the joy of roller skating is accessible to all.

Our Coaches
James McAvoy
- 5 years experience
- Beginner and Intermediate Instructor
- Figure Skating background

Adam Jones
- 10 years experience
- Intermediate and Advanced Instructor
- Wizard and Urban Skating background

Siobhan Conner
- 25 years experience
- Advanced Instructor
- Olympian and 2x World Championship
- Certified Physiotherapist and nutritionist

Beginner 1
Location : Big Island Sports Complex
Date :
Time :
Suitable for : This class is suitable for absolute beginners on skates. 
You will learn
- Stand up and falling
- Moving fowards
- How to stop

Beginner 2
Location : Big Island Sports Complex
Date :
Time :
Suitable for : This class is for beginners skater who passed Beginner 1.
You will learn
- Moving backwards
- Skating on one foot
- Turning on two feet

Intermediate 1
Location : Saturn Stadium
Date :
Time :
Suitable for : This class is suitable skaters who have passed all beginner levels or able to execute the following skills; three turns, crossover, mohwak. 
You will learn
- Forward Otters
- Dribbles
- Uptown

Intermediate 2
Location : Saturn Stadium
Date :
Time :
Suitable for : This class is suitable skaters who have passed Intermediate 1.
You will learn
- Outside Lion
- Crazy Legs
- Stalk Spin

Advance 1
Location : Pairc Ui Padraig
Date :
Time :
Suitable for : This class is suitable skaters who have passed all intermediate level or able to execute the following skills; Flip, Manuals, Gazelle
You will learn
- Single Otter 
- Death Spiral
- Twist Flip
- 
Competition
Location : Pairc Ui Padraig
Date :
Time :
Suitable for : This class is suitable skaters for competition skater only.
You will work with the coach to personalise, choreograph, and master your program to be competition-ready.

**Comment by yamesjamess** [comment]
Images

Home page
https://www.pexels.com/photo/two-smiling-girls-on-roller-skates-8733145/

Coaches
Roisin
https://www.pexels.com/photo/woman-wearing-green-short-jumpsuit-holding-her-roller-skates-8734204/
James
https://www.pexels.com/photo/man-in-black-and-white-button-up-shirt-and-yellow-pants-7335210/
Adam
https://www.pexels.com/photo/a-man-in-brown-pants-sitting-on-the-street-while-wearing-rollerblades-7335160/
Siobhan
https://www.pexels.com/photo/woman-in-blue-and-white-stripe-shirt-and-white-shorts-standing-beside-pink-wall-7335310/

About Us
https://www.pexels.com/photo/cheerful-girl-skating-on-rollers-with-young-mother-4127353/

Big Island Sports Complex
https://unsplash.com/photos/b1zmP0emxNk

Saturn Stadium
https://unsplash.com/photos/oD28og2H8M0

Seomra Ui Padraig
https://unsplash.com/photos/f6qvFwMADyk

**Comment by yamesjamess** [comment]
Color Scheme

![Image](https://github.com/yamesjamess/p4-untitled/assets/79316002/2b283c5f-cea2-4df4-aa35-14860c134d69)

**Comment by yamesjamess** [comment]
Font 
Kodchasan

**Comment by yamesjamess** [comment]
Bootstrap theme
https://bootstrapmade.com/flattern-multipurpose-bootstrap-template/

**Comment by yamesjamess** [comment]
ER Diagram
![image](https://github.com/yamesjamess/p4-untitled/assets/79316002/b2cb0543-eb51-4496-a8e6-97abf543ec0e)

**Comment by yamesjamess** [comment]
Place holder featured image
https://www.pexels.com/photo/white-and-red-roller-skates-2005992/

**Comment by yamesjamess** [comment]
https://maketintsandshades.com/#BF4B53

**Comment by yamesjamess** [comment]
christmas image
https://www.pexels.com/photo/closeup-photography-of-christmas-bauble-hanging-on-tree-724906/
